version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "miniconda3-3.12-24.9"

conda:
  environment: environment.yml

sphinx:
  configuration: docs/conf.py
  builder: html
  fail_on_warning: true
